version: '3'

services: 

  horseserver:
    build: .
    image: souzadeveloper/horseserver
    container_name: horseserver
    entrypoint: ./HorseServer
    privileged: true 
    tty: true
    ports:
      - 9000:9000